## 向量化和广播
向量化和广播这两个概念是 numpy 内部实现的基础。有了向量化，编写代码时无需使用显式循环。这些循环实际上不能省略，只不过是在内部实现，被代码中的其他结构代替。向量化的应用使得代码更简洁，可读性更强，也可以说使用了向量化方法的代码看上去更“Pythonic”。

广播（Broadcasting）机制描述了 numpy 如何在算术运算期间处理具有不同形状的数组，让较小的数组在较大的数组上“广播”，以便它们具有兼容的形状。并不是所有的维度都要彼此兼容才符合广播机制的要求，但它们必须满足一定的条件。

若两个数组的各维度兼容，也就是两个数组的每一维等长，或其中一个数组为 一维，那么广播机制就适用。如果这两个条件不满足，numpy就会抛出异常，说两个数组不兼容。

总结来说，广播的规则有三个：

- 如果两个数组的维度数dim不相同，那么小维度数组的形状将会在左边补1。
- 如果shape维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；
- 如果shape维度不匹配，但是没有任何一个维度是1，则匹配引发错误；

In [4]:
import numpy as np
x=np.arange(4)
y=np.ones((3,4))
print(x.shape)
print(y.shape)
print('============1==============')
print((x+y).shape)
print('=============2=============')
print(x+y)

(4,)
(3, 4)
============1==============
(3, 4)
=============2=============
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [7]:
x=np.arange(4).reshape(4,1)
y=np.ones(5)  # 一维数组
print(x.shape)
print(y.shape)
print('==================1================')
print((x+y).shape)
print(x+y)
print('===============2===================')
x=np.array([0.1,10.0,20.0,30.0])
y=np.array([1.0,2.0,3.0])
z=x[:,np.newaxis]+y
print(z)

(4, 1)
(5,)
==================1================
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
===============2===================
[[ 1.1  2.1  3.1]
 [11.  12.  13. ]
 [21.  22.  23. ]
 [31.  32.  33. ]]


## 数学函数
### 算术运算

加减乘除
- numpy.add(x1, x2, * args, ** kwargs) 
- numpy.subtract(x1, x2, * args, ** kwargs) 
- numpy.multiply(x1, x2, * args, ** kwargs) 
- numpy.divide(x1, x2, * args, ** kwargs)
- numpy.floor_divide(x1, x2, * args, ** kwargs) 
- numpy.power(x1, x2, * args, ** kwargs)

这里的加减乘除都是数组元素之间的运算，结果是一个新的数组

In [12]:
x=np.array([1,2,3,4,5,6,7,8])
y=x+1
print('=========加法==================')
print(y)
print(np.add(x,1))
print('=============减法================')
y=x-1
print(y)
print(np.subtract(x,1))
print('===============乘法===============')
y=x*2
print(y)
print(np.multiply(x,2))
print('===========除法=======================')
y=x/2
print(y)
print(np.divide(x,2))
print('===========除法商==================')
y=x//2
print(y)
print(np.floor_divide(x,2))
print('========================二次幂====================')
y=x**2
print(y)
print(np.power(x,2))

=========加法==================
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
=============减法================
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
===============乘法===============
[ 2  4  6  8 10 12 14 16]
[ 2  4  6  8 10 12 14 16]
===========除法=======================
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
===========除法商==================
[0 1 1 2 2 3 3 4]
[0 1 1 2 2 3 3 4]
========================二次幂====================
[ 1  4  9 16 25 36 49 64]
[ 1  4  9 16 25 36 49 64]


In [13]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y=x+1
print('=========加法==================')
print(y)
print(np.add(x,1))
print('=============减法================')
y=x-1
print(y)
print(np.subtract(x,1))
print('===============乘法===============')
y=x*2
print(y)
print(np.multiply(x,2))
print('===========除法=======================')
y=x/2
print(y)
print(np.divide(x,2))
print('===========除法商==================')
y=x//2
print(y)
print(np.floor_divide(x,2))
print('========================二次幂====================')
y=x**2
print(y)
print(np.power(x,2))

=========加法==================
[[ 12  23  34  45  56]
 [ 67  78  89 100  99]
 [ 13  24  35  46  57]
 [ 68  79  90  91 100]
 [ 88  87  86  85  84]]
[[ 12  23  34  45  56]
 [ 67  78  89 100  99]
 [ 13  24  35  46  57]
 [ 68  79  90  91 100]
 [ 88  87  86  85  84]]
=============减法================
[[10 21 32 43 54]
 [65 76 87 98 97]
 [11 22 33 44 55]
 [66 77 88 89 98]
 [86 85 84 83 82]]
[[10 21 32 43 54]
 [65 76 87 98 97]
 [11 22 33 44 55]
 [66 77 88 89 98]
 [86 85 84 83 82]]
===============乘法===============
[[ 22  44  66  88 110]
 [132 154 176 198 196]
 [ 24  46  68  90 112]
 [134 156 178 180 198]
 [174 172 170 168 166]]
[[ 22  44  66  88 110]
 [132 154 176 198 196]
 [ 24  46  68  90 112]
 [134 156 178 180 198]
 [174 172 170 168 166]]
===========除法=======================
[[ 5.5 11.  16.5 22.  27.5]
 [33.  38.5 44.  49.5 49. ]
 [ 6.  11.5 17.  22.5 28. ]
 [33.5 39.  44.5 45.  49.5]
 [43.5 43.  42.5 42.  41.5]]
[[ 5.5 11.  16.5 22.  27.5]
 [33.  38.5 44.  49.5 49. ]
 [ 6.  11.5 17.  22.5 28.

In [14]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y=np.arange(1,6)
print(y)


[1 2 3 4 5]


In [15]:
z=x-y
print(z)
print(np.subtract(x,y))

[[10 20 30 40 50]
 [65 75 85 95 93]
 [11 21 31 41 51]
 [66 76 86 86 94]
 [86 84 82 80 78]]
[[10 20 30 40 50]
 [65 75 85 95 93]
 [11 21 31 41 51]
 [66 76 86 86 94]
 [86 84 82 80 78]]


In [16]:
z=x*y
print(z)
print(np.multiply(x,y))


[[ 11  44  99 176 275]
 [ 66 154 264 396 490]
 [ 12  46 102 180 280]
 [ 67 156 267 360 495]
 [ 87 172 255 336 415]]
[[ 11  44  99 176 275]
 [ 66 154 264 396 490]
 [ 12  46 102 180 280]
 [ 67 156 267 360 495]
 [ 87 172 255 336 415]]


In [17]:
z=x/y
print(z)
print(np.divide(x,y))

[[11.         11.         11.         11.         11.        ]
 [66.         38.5        29.33333333 24.75       19.6       ]
 [12.         11.5        11.33333333 11.25       11.2       ]
 [67.         39.         29.66666667 22.5        19.8       ]
 [87.         43.         28.33333333 21.         16.6       ]]
[[11.         11.         11.         11.         11.        ]
 [66.         38.5        29.33333333 24.75       19.6       ]
 [12.         11.5        11.33333333 11.25       11.2       ]
 [67.         39.         29.66666667 22.5        19.8       ]
 [87.         43.         28.33333333 21.         16.6       ]]


In [18]:
z=x//y
print(z)
print(np.floor_divide(x,y))


[[11 11 11 11 11]
 [66 38 29 24 19]
 [12 11 11 11 11]
 [67 39 29 22 19]
 [87 43 28 21 16]]
[[11 11 11 11 11]
 [66 38 29 24 19]
 [12 11 11 11 11]
 [67 39 29 22 19]
 [87 43 28 21 16]]


In [19]:
z=x**np.full([1,5],2)
print(z)
print(np.power(x,np.full([5,5],2)))

[[ 121  484 1089 1936 3025]
 [4356 5929 7744 9801 9604]
 [ 144  529 1156 2025 3136]
 [4489 6084 7921 8100 9801]
 [7569 7396 7225 7056 6889]]
[[ 121  484 1089 1936 3025]
 [4356 5929 7744 9801 9604]
 [ 144  529 1156 2025 3136]
 [4489 6084 7921 8100 9801]
 [7569 7396 7225 7056 6889]]


In [21]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y=np.arange(1,26).reshape([5,5])
print(y)
z=x+y
print('=========加法==================')
print(z)
print(np.add(x,y))
print('=============减法================')
z=x-y
print(z)
print(np.subtract(x,y))
print('===============乘法===============')
z=x*y
print(z)
print(np.multiply(x,y))
print('===========除法=======================')
z=x/y
print(z)
print(np.divide(x,y))
print('===========除法商==================')
z=x//y
print(z)
print(np.floor_divide(x,y))
print('========================二次幂====================')
z=x**np.full([5,5],2)
print(z)
print(np.power(x,np.full([5,5],2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
=========加法==================
[[ 12  24  36  48  60]
 [ 72  84  96 108 108]
 [ 23  35  47  59  71]
 [ 83  95 107 109 119]
 [108 108 108 108 108]]
[[ 12  24  36  48  60]
 [ 72  84  96 108 108]
 [ 23  35  47  59  71]
 [ 83  95 107 109 119]
 [108 108 108 108 108]]
=============减法================
[[10 20 30 40 50]
 [60 70 80 90 88]
 [ 1 11 21 31 41]
 [51 61 71 71 79]
 [66 64 62 60 58]]
[[10 20 30 40 50]
 [60 70 80 90 88]
 [ 1 11 21 31 41]
 [51 61 71 71 79]
 [66 64 62 60 58]]
===============乘法===============
[[  11   44   99  176  275]
 [ 396  539  704  891  980]
 [ 132  276  442  630  840]
 [1072 1326 1602 1710 1980]
 [1827 1892 1955 2016 2075]]
[[  11   44   99  176  275]
 [ 396  539  704  891  980]
 [ 132  276  442  630  840]
 [1072 1326 1602 1710 1980]
 [1827 1892 1955 2016 2075]]
===========除法=======================
[[11.         11.         11.         11.         11.        ]
 [11.         11. 

### numpy.sqrt
### numpy.square
- numpy.sqrt(x, * args, ** kwargs) 
- numpy.square(x, * args, ** kwargs)

In [22]:
x=np.arange(1,5)
print(x)
print('=============开方================')
y=np.sqrt(x)
print(y)
print(np.power(x,0.5))
print('==================平方==========')
y=np.square(x)
print(y)
print(np.power(x,2))

[1 2 3 4]
=============开方================
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]
==================平方==========
[ 1  4  9 16]
[ 1  4  9 16]


## 三角函数
- cos
- sin
- tan
- arcsin
- arccos
- arctan
- numpy.sin(x, * args, ** kwargs)  
- numpy.cos(x, * args, ** kwargs)  
- numpy.tan(x, * args, ** kwargs)  
- numpy.arcsin(x, * args, ** kwargs)  
- numpy.arccos(x, * args, ** kwargs)  
- numpy.arctan(x, * args, ** kwargs) 

通用函数（universal function）通常叫作ufunc，它对数组中的各个元素逐一进行操作。这表明，通用函数分别处理输入数组的每个元素，生成的结果组成一个新的输出数组。输出数组的大小跟输入数组相同。

三角函数等很多数学运算符合通用函数的定义，例如，计算平方根的sqrt()函数、用来取对数的log()函数和求正弦值的sin()函数。

In [31]:
x=np.linspace(start=0,stop=np.pi/2,num=10)
print(x)
print('=======sin=============')
y=np.sin(x)
print(y)

print('=======arcsin=============')
z=np.arcsin(y)
print(z)

print('=======cos=============')
y=np.cos(x)
print(y)

print('=======arccos=============')
z=np.arccos(y)
print(z)

print('=======tan=============')
y=np.tan(x)
print(y)
print('=======arctan=============')
z=np.arctan(y)
print(z)

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
=======sin=============
[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]
=======arcsin=============
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
=======cos=============
[1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
 7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
 1.73648178e-01 6.12323400e-17]
=======arccos=============
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]
=======tan=============
[0.00000000e+00 1.76326981e-01 3.63970234e-01 5.77350269e-01
 8.39099631e-01 1.19175359e+00 1.73205081e+00 2.74747742e+00
 5.67128182e+00 1.63312394e+16]
=======arctan=============
[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.221730

## 指数和对数

- numpy.exp(x, * args, ** kwargs)  
- numpy.log(x, * args, ** kwargs)  
- numpy.exp2(x, * args, ** kwargs)   
- numpy.log2(x, * args, ** kwargs) 
- numpy.log10(x, * args, ** kwargs)

In [32]:
x=np.arange(1,5)
print(x)
y=np.exp(x)
print(y)
z=np.log(y)
print(z)

[1 2 3 4]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1. 2. 3. 4.]


## 加法函数、乘法函数
- numpy.sum(a[, axis=None, dtype=None, out=None, …])

通过不同的 axis，numpy 会沿着不同的方向进行操作：如果不设置，那么对所有的元素操作；如果axis=0，则沿着纵轴进行操作；axis=1，则沿着横轴进行操作。但这只是简单的二位数组，如果是多维的呢？可以总结为一句话：设axis=i，则 numpy 沿着第i个下标变化的方向进行操作。
- numpy.cumsum(a, axis=None, dtype=None, out=None) 

聚合函数 是指对一组值（比如一个数组）进行操作，返回一个单一值作为结果的函数。因而，求数组所有元素之和的函数就是聚合函数。ndarray类实现了多个这样的函数。

In [34]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y=np.sum(x)
print(y)
y=np.sum(x,axis=0)
print(y)
y=np.sum(x,axis=1)
print(y)

1611
[243 286 329 362 391]
[165 428 170 423 425]


In [36]:
y=np.cumsum(x)
print(y)
# 逐个相加得到结果

[  11   33   66  110  165  231  308  396  495  593  605  628  662  707
  763  830  908  997 1087 1186 1273 1359 1444 1528 1611]


In [38]:
y=np.cumsum(x,axis=0)
print('==============x轴=================')
print(y)
print('=========y轴====================')
y=np.cumsum(x,axis=1)
print(y)

==============x轴=================
[[ 11  22  33  44  55]
 [ 77  99 121 143 153]
 [ 89 122 155 188 209]
 [156 200 244 278 308]
 [243 286 329 362 391]]
=========y轴====================
[[ 11  33  66 110 165]
 [ 66 143 231 330 428]
 [ 12  35  69 114 170]
 [ 67 145 234 324 423]
 [ 87 173 258 342 425]]


### numpy.prod乘积
### numpy.cumprod累乘
- numpy.prod(a[, axis=None, dtype=None, out=None, …]) 
- numpy.cumprod(a, axis=None, dtype=None, out=None) 

In [39]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y=np.prod(x)
print(y)
y=np.prod(x,axis=0)
print('===========x轴============')
print(y)
print('==============y轴==========')
y=np.prod(x,axis=1)
print(y)

-182976512
===========x轴============
[   50782248   261357096   746937840  1481911200 -1814748016]
==============y轴==========
[  19326120   43922336   23647680 -150801556  139015544]


In [41]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])

y=np.cumprod(x)
print(y)
print('================x轴=-=============')
y=np.cumprod(x,axis=0)
print(y)
print('=================y轴===============')
y=np.cumprod(x,axis=1)
print(y)

[         11         242        7986      351384    19326120  1275523920
  -568905968  1475882368    83466368  -410230528  -627799040 -1554476032
 -1312577536  1063553024  -570572800   426328064 -1106149376   336953344
   261029888    72155136  1982529536 -1301151744  1071251456  -209190912
  -182976512]
================x轴=-=============
[[         11          22          33          44          55]
 [        726        1694        2904        4356        5390]
 [       8712       38962       98736      196020      301840]
 [     583704     3039036     8787504    17641800    29882160]
 [   50782248   261357096   746937840  1481911200 -1814748016]]
=================y轴===============
[[        11        242       7986     351384   19326120]
 [        66       5082     447216   44274384   43922336]
 [        12        276       9384     422280   23647680]
 [        67       5226     465114   41860260 -150801556]
 [        87       7482     635970   53421480  139015544]]


### numpy.diff差值
- numpy.diff(a, n=1, axis=-1, prepend=np._NoValue, append=np._NoValue) Calculate the n-th discrete difference along the given axis.
- a：输入矩阵
- n：可选，代表要执行几次差值
- axis：默认是最后一个

In [45]:
A=np.arange(2,14).reshape((3,4))
A[1,1]=9
print(A)
print('===================')
print(np.diff(A))
print('================-====')
print(np.diff(A,axis=0))

[[ 2  3  4  5]
 [ 6  9  8  9]
 [10 11 12 13]]
[[ 1  1  1]
 [ 3 -1  1]
 [ 1  1  1]]
================-====
[[4 6 4 4]
 [4 2 4 4]]


## 四舍五入
- numpy.around(a, decimals=0, out=None)

In [47]:
x=np.random.rand(3,3)*10
print(x)
print('========================')
y=np.around(x)
print(y)
print('========================')
y=np.around(x,decimals=2)
print(y)

[[1.3449908  4.77993765 1.55931241]
 [5.48566023 2.84619462 3.88413994]
 [2.06060411 1.93706877 5.80979413]]
[[1. 5. 2.]
 [5. 3. 4.]
 [2. 2. 6.]]
[[1.34 4.78 1.56]
 [5.49 2.85 3.88]
 [2.06 1.94 5.81]]


### 上下限
- numpy.ceil(x, * args, ** kwargs)  
- numpy.floor(x, * args, ** kwargs)

In [50]:
x = np.random.rand(3, 3) * 10
print(x)
print('===========================')
y = np.ceil(x)
print(y)
print('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-')
y = np.floor(x)
print(y)

[[9.55469037e+00 7.46074074e-01 6.66767878e+00]
 [4.21708963e+00 7.83560126e+00 1.21613124e+00]
 [7.49007737e+00 9.51476588e+00 5.20941262e-03]]
[[10.  1.  7.]
 [ 5.  8.  2.]
 [ 8. 10.  1.]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[[9. 0. 6.]
 [4. 7. 1.]
 [7. 9. 0.]]


### 杂项  
- numpy.clip(a, a_min, a_max, out=None, ** kwargs)

In [51]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])
y = np.clip(x, a_min=20, a_max=30)
print(y)

[[20 22 30 30 30]
 [30 30 30 30 30]
 [20 23 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]


- numpy.absolute(x, * args, ** kwargs)  
- numpy.abs(x, * args, ** kwargs)  

In [53]:
x=np.arange(-5,5)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [54]:
y = np.abs(x)
print(y)

[5 4 3 2 1 0 1 2 3 4]


In [55]:
y = np.absolute(x)
print(y)

[5 4 3 2 1 0 1 2 3 4]


### numpy.sign 返回数字符号的逐元素指示
- numpy.sign(x, * args, ** kwargs)  

In [57]:
x = np.arange(-5, 5)
print(x)
print(np.sign(x))

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-1 -1 -1 -1 -1  0  1  1  1  1]


##  逻辑函数
- numpy.all(a, axis=None, out=None, keepdims=np._NoValue)  
- numpy.any(a, axis=None, out=None, keepdims=np._NoValue)

In [58]:
a = np.array([0, 4, 5])
b = np.copy(a)
print(np.all(a == b))  

print(np.any(a == b))

True
True


In [59]:
b[0] = 1
print(np.all(a == b))   

print(np.any(a == b)) 

False
True


In [60]:
print(np.all([1.0, np.nan]))  
print(np.any([1.0, np.nan]))

True
True


In [61]:
a = np.eye(3)
print(np.all(a, axis=0))   
print(np.any(a, axis=0))  

[False False False]
[ True  True  True]


### 数组内容
- numpy.isnan(x, * args, ** kwargs)

In [62]:
a=np.array([1,2,np.nan])
print(np.isnan(a))

[False False  True]


## 逻辑运算
- numpy.logical_not(x, * args, ** kwargs) 
- numpy.logical_and(x1, x2, * args, ** kwargs)  
- numpy.logical_or(x1, x2, * args, ** kwargs) 
- numpy.logical_xor(x1, x2, * args, ** kwargs)

In [63]:
print(np.logical_not(3))  
 
print(np.logical_not([True, False, 0, 1]))

False
[False  True  True False]


In [64]:
x = np.arange(5)
print(np.logical_not(x < 3))

[False False False  True  True]


In [65]:
print(np.logical_and(True, False))  
 
print(np.logical_and([True, False], [True, False]))
 
print(np.logical_and(x > 1, x < 4))
 

False
[ True False]
[False False  True  True False]


In [66]:
print(np.logical_or(True, False))
 
print(np.logical_or([True, False], [False, False]))
 
print(np.logical_or(x < 1, x > 3))

True
[ True False]
[ True False False False  True]


In [67]:
print(np.logical_xor(True, False))
 
print(np.logical_xor([True, True, False, False], [True, False, True, False]))
 
print(np.logical_xor(x < 1, x > 3))
 
print(np.logical_xor(0, np.eye(2)))

True
[False  True  True False]
[ True False False False  True]
[[ True False]
 [False  True]]


### 对照
- numpy.greater(x1, x2, * args, ** kwargs)  
- numpy.greater_equal(x1, x2, * args, ** kwargs)  
- numpy.equal(x1, x2, * args, ** kwargs)  
- numpy.not_equal(x1, x2, * args, ** kwargs)  
- numpy.less(x1, x2, * args, ** kwargs)  
- numpy.less_equal(x1, x2, * args, ** kwargs) 

In [68]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

y = x > 2
print(y)
print(np.greater(x, 2))

[False False  True  True  True  True  True  True]
[False False  True  True  True  True  True  True]


In [69]:
y = x >= 2
print(y)
print(np.greater_equal(x, 2))

[False  True  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True]


In [70]:
y = x == 2
print(y)
print(np.equal(x, 2))

[False  True False False False False False False]
[False  True False False False False False False]


In [71]:
y = x != 2
print(y)
print(np.not_equal(x, 2))

[ True False  True  True  True  True  True  True]
[ True False  True  True  True  True  True  True]


In [72]:
y = x < 2
print(y)
print(np.less(x, 2))

[ True False False False False False False False]
[ True False False False False False False False]


In [73]:
y = x <= 2
print(y)
print(np.less_equal(x, 2))

[ True  True False False False False False False]
[ True  True False False False False False False]


In [76]:
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])


In [77]:
y = x > 20
print(y)
print(np.greater(x, 20))

[[False  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [78]:
y = x >= 20
print(y)
print(np.greater_equal(x, 20))

[[False  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False  True  True  True  True]
 [ True  True  True  True  True]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [79]:
y = x == 20
print(y)
print(np.equal(x, 20))

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [80]:
y = x != 20
print(y)
print(np.not_equal(x, 20))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [81]:
y = x < 20
print(y)
print(np.less(x, 20))

[[ True False False False False]
 [False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]
[[ True False False False False]
 [False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]


In [82]:
y = x <= 20
print(y)
print(np.less_equal(x, 20))

[[ True False False False False]
 [False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]
[[ True False False False False]
 [False False False False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]


In [84]:
np.random.seed(920200611)
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])


In [85]:
y = np.random.randint(10, 40, [5, 5])
print(y)

[[17 32 14 29 14]
 [28 33 36 14 37]
 [21 34 24 20 28]
 [21 23 27 25 26]
 [25 30 15 25 37]]


In [86]:
z = x > y
print(z)
print(np.greater(x, y))

[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [87]:
z = x >= y
print(z)
print(np.greater_equal(x, y))

[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [88]:
z = x == y
print(z)
print(np.equal(x, y))

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [89]:
z = x != y
print(z)
print(np.not_equal(x, y))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [90]:
z = x < y
print(z)
print(np.less(x, y))

[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]


In [91]:
z = x <= y
print(z)
print(np.less_equal(x, y))

[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]


In [92]:
np.random.seed(920200611)
x=np.array([[11,22,33,44,55],
           [66,77,88,99,98],
           [12,23,34,45,56],
           [67,78,89,90,99],
           [87,86,85,84,83]])


In [93]:
np.random.seed(20200611)
y = np.random.randint(10, 50, 5)

print(y)

[32 37 30 24 10]


In [94]:
z = x > y
print(z)
print(np.greater(x, y))

[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [95]:
z = x >= y
print(z)
print(np.greater_equal(x, y))

[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False  True  True  True]
 [ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [96]:
z = x == y
print(z)
print(np.equal(x, y))

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [97]:
z = x != y
print(z)
print(np.not_equal(x, y))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [98]:
z = x < y
print(z)
print(np.less(x, y))

[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]


In [99]:
z = x <= y
print(z)
print(np.less_equal(x, y))


[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True False False False]
 [False False False False False]
 [ True  True False False False]
 [False False False False False]
 [False False False False False]]


- numpy.isclose(a, b, rtol=1.e-5, atol=1.e-8, equal_nan=False)  
- numpy.allclose(a, b, rtol=1.e-5, atol=1.e-8, equal_nan=False) 
- numpy.allclose() 等价于 numpy.all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))。

In [100]:
x = np.isclose([1e10, 1e-7], [1.00001e10, 1e-8])
print(x)   

[ True False]


In [101]:
x = np.allclose([1e10, 1e-7], [1.00001e10, 1e-8])
print(x) 

False


In [102]:
x = np.isclose([1e10, 1e-8], [1.00001e10, 1e-9])
print(x)

[ True  True]


In [103]:
x = np.allclose([1e10, 1e-8], [1.00001e10, 1e-9])
print(x)

True


In [104]:
x = np.isclose([1e10, 1e-8], [1.0001e10, 1e-9])
print(x)

[False  True]


In [105]:
x = np.allclose([1e10, 1e-8], [1.0001e10, 1e-9])
print(x)  

False


In [106]:
x = np.isclose([1.0, np.nan], [1.0, np.nan])
print(x) 

[ True False]


In [107]:
x = np.allclose([1.0, np.nan], [1.0, np.nan])
print(x)

False


In [108]:
x = np.isclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
print(x) 

[ True  True]


In [109]:
x = np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
print(x) 

True
