# 导入numpy
numpy是一个python的工具包，主要应用于处理数组类型的数据

In [1]:
import numpy as np

## 常量
- numpy.nan
- numpy.inf
- numpy.pi
- numpy.e

### numpy.nan 空值
在实际应用中用到最多是nan空值，在数据处理中涉及到对空值的处理，

In [2]:
A=[0,2,4,np.nan]
A

[0, 2, 4, nan]

空值也占一个长度

In [3]:
len(A)

4

判断数组中是否用空值可以用np.isnan()函数，它会按照索引位置返回空值的判断，空值为True

In [4]:
print(np.isnan(A))

[False False False  True]


在实际数据挖掘的过程中可以用sum()统计空值的数量，并对其进行处理

count_nonzero()对非0元素统计

In [5]:
print(np.isnan(A).sum())

1


In [6]:
z = np.count_nonzero(A)
z

3

### inf是无穷大
在对比大小的时候比任何数都大

In [7]:
c=np.inf
print(c>9999999999)

True


### pi是圆周率
可以用pi求解圆的面积

In [8]:
d=np.pi
d
r=10

In [9]:
s=d*r*r
s

314.1592653589793

### e自然数，对数函数

In [10]:
import math
f=np.e*np.e
g=math.log(f)
g

2.0

## 数据类型
>常见的数据类型有整型、浮点型、字符串、布尔型等等

>python的原生数据类型较少bool、int、float、str,原生的数据类型在类型名称后都加了'_'

- bool_=bool8
- int_=int64=long=int0=intp
- float_=float64=double
- str_=unicode=str0


所以需要创建数据类型

每一个自建的数据类型都有一个唯一的字符代码
- boolean--'b1
- signed integer--'i1','i2','i4','i8'
- floating-point--'f2','f4','f8'
- unsigned integer--'u1','u2','u4','u8'
- string--S3表示长度为3的字符串

In [11]:
a=np.dtype('b1')
a

dtype('bool')

In [12]:
a=np.dtype('i1')
a

dtype('int8')

In [13]:
a=np.dtype('i2')
a

dtype('int16')

In [14]:
a=np.dtype('i4')
a

dtype('int32')

In [15]:
a=np.dtype('i8')
a

dtype('int64')

In [16]:
a=np.dtype('f2')
a

dtype('float16')

In [17]:
a=np.dtype('f4')
a

dtype('float32')

In [18]:
a=np.dtype('f8')
a

dtype('float64')

In [19]:
a=np.dtype('u1')
a

dtype('uint8')

In [20]:
a=np.dtype('u2')
a

dtype('uint16')

In [21]:
a=np.dtype('u4')
a

dtype('uint32')

In [22]:
a=np.dtype('u8')
a

dtype('uint64')

In [23]:
a=np.dtype('S')
a1=a.type
a2=a.itemsize
a1,a2

(numpy.bytes_, 0)

In [24]:
a=np.dtype('S3')
a1=a.type
a2=a.itemsize
a1,a2

(numpy.bytes_, 3)

In [25]:
a=np.dtype('U3')
a1=a.type
a2=a.itemsize
a1,a2

(numpy.str_, 12)

### 日期和时间增量

In [26]:
a=np.datetime64('2020-10-10')
a,a.dtype

(numpy.datetime64('2020-10-10'), dtype('<M8[D]'))

In [27]:
a=np.datetime64('2020-10')
a,a.dtype

(numpy.datetime64('2020-10'), dtype('<M8[M]'))

In [28]:
a=np.datetime64('2020')
a,a.dtype

(numpy.datetime64('2020'), dtype('<M8[Y]'))

In [29]:
a=np.datetime64('2020-10-10 20:10:30')
a,a.dtype

(numpy.datetime64('2020-10-10T20:10:30'), dtype('<M8[s]'))

In [30]:
a=np.datetime64('2020-10-10 20:10')
a,a.dtype

(numpy.datetime64('2020-10-10T20:10'), dtype('<M8[m]'))

In [31]:
a=np.datetime64('2020-10-10 20')
a,a.dtype

(numpy.datetime64('2020-10-10T20','h'), dtype('<M8[h]'))

In [32]:
a=np.datetime64('2020-10-10 20:10','Y')
a,a.dtype

(numpy.datetime64('2020'), dtype('<M8[Y]'))

In [33]:
a=np.datetime64('2020-10-10 20:10','D')
a,a.dtype

(numpy.datetime64('2020-10-10'), dtype('<M8[D]'))

In [34]:
a=np.datetime64('2020-10-10 20:10','s')
a,a.dtype

(numpy.datetime64('2020-10-10T20:10:00'), dtype('<M8[s]'))

### 使用arange（）方法生成日期范围
可以由日到日，也可以有小时到小时

In [35]:
a=np.arange('2020-10-01','2020-10-10',dtype=np.datetime64)
a,a.dtype

(array(['2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04',
        '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
        '2020-10-09'], dtype='datetime64[D]'),
 dtype('<M8[D]'))

### timedelta64运算
对日期时间都可以进行计算，加减时间

In [36]:
a = np.datetime64('2020-10-10') - np.datetime64('2020-10-01')
b = np.datetime64('2020-10-10') - np.datetime64('2020-03-07 08:00')
c = np.datetime64('2020-03-08') - np.datetime64('2020-03-07 23:00', 'D')

In [37]:
print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)

9 days timedelta64[D]
312000 minutes timedelta64[m]
1 days timedelta64[D]


In [38]:
a = np.datetime64('2020-10') + np.timedelta64(20, 'D')
b = np.datetime64('2020-10-10 00:00') + np.timedelta64(12, 'h')

In [39]:
print(a,a.dtype)
print(b,b.dtype)


2020-10-21 datetime64[D]
2020-10-10T12:00 datetime64[m]


### 工作日与休息日

In [40]:
a = np.busday_offset('2020-10-10', offsets=1,roll='forward')
a

numpy.datetime64('2020-10-13')

如果日期刚好是工作日，那么就直接输出日期，如果，非工作日，可以通过设置roll=forward或者roll=backward参数来设置往前还是往后找工作日

#### 统计数组中的工作日天数

In [41]:
begindates = np.datetime64('2020-10-01')
enddates = np.datetime64('2020-10-20')
a = np.arange(begindates, enddates, dtype='datetime64')
b = np.count_nonzero(np.is_busday(a))
c=np.is_busday(a)
print(a)
print(len(a))
print(b)
print(c)

['2020-10-01' '2020-10-02' '2020-10-03' '2020-10-04' '2020-10-05'
 '2020-10-06' '2020-10-07' '2020-10-08' '2020-10-09' '2020-10-10'
 '2020-10-11' '2020-10-12' '2020-10-13' '2020-10-14' '2020-10-15'
 '2020-10-16' '2020-10-17' '2020-10-18' '2020-10-19']
19
13
[ True  True False False  True  True  True  True  True False False  True
  True  True  True  True False False  True]


这里有点小问题，今年十一国庆明明是8天的假期，但是，这里显示，只有6天的假期，有点不懂为什么,而且查看后发现，这个函数代码好像不分国界，没有国庆节，只是默认的工作日和周末

指定工作日

In [42]:
a = np.is_busday('2020-10-02', weekmask=[1, 1, 1, 1, 1, 0, 0])
b = np.is_busday('2020-10-02', weekmask=[1, 1, 1, 1, 0, 0, 1])
print(a)
print(b)

True
False


统计两个日期之间的工作日

## 数组创建
numpy提供的最重要的数据结构是ndarray，它是python中list的扩展

### 依据现有数据来创建ndarray

创建一维数组

In [43]:
a=np.array([0,1,2,3,4])
b=np.array([0,1,2,3,4])
print(a,type(a))
print(b,type(b))

[0 1 2 3 4] <class 'numpy.ndarray'>
[0 1 2 3 4] <class 'numpy.ndarray'>


创建二维数组

In [44]:
c=np.array([[11,22,33,44,55],
  [12,23,34,45,56],
  [21,32,43,54,65],
  [12,13,14,15,16],
  [21,22,23,24,25]])
print(c,type(c))

[[11 22 33 44 55]
 [12 23 34 45 56]
 [21 32 43 54 65]
 [12 13 14 15 16]
 [21 22 23 24 25]] <class 'numpy.ndarray'>


创建三维数组

In [45]:
d=np.array([[(1,3,5),(4,5,6)],
           [(7,8,9),(3,5,8)]])
print(d,type(d))

[[[1 3 5]
  [4 5 6]]

 [[7 8 9]
  [3 5 8]]] <class 'numpy.ndarray'>


### 通过asarray（）函数创建数组

In [46]:
x=[[1,1,1],[2,2,2],[3,3,3]]
y=np.array(x)
z=np.asarray(x)
x[1][2]=9
print(x,type(x))
print(y,type(y))
print(z,type(z))

[[1, 1, 1], [2, 2, 9], [3, 3, 3]] <class 'list'>
[[1 1 1]
 [2 2 2]
 [3 3 3]] <class 'numpy.ndarray'>
[[1 1 1]
 [2 2 2]
 [3 3 3]] <class 'numpy.ndarray'>


In [47]:
a=np.ones((3,3))
b=np.array(a)
c=np.asarray(a)
a[2][2]=9
print(a,type(a))
print(b,type(b))
print(c,type(c))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 9.]] <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 9.]] <class 'numpy.ndarray'>


由此可见array()和asarray()主要区别就是当数据源是ndarray 时，array()仍然会 copy 出一个副本，占用新的内存，但不改变 dtype 时 asarray()不会返回的还是原来的数组a
。

### 通过fromfunction（）函数创建

In [48]:
def f(x,y):
    return 10*x+y

x=np.fromfunction(f,(5,4),dtype=int)
print(x)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [49]:
x = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
# 数组元素个位十位数字相同
print(x)

[[ True False False]
 [False  True False]
 [False False  True]]


In [50]:
x = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 初始化依据ones和zeros填充方式

- 0数组

In [51]:
x=np.zeros(5)
print(x,type(x))

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [52]:
x=np.zeros([2,3])
print(x,type(x))

[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [53]:
x=np.array([[1,2,3],
          [4,5,6]])
y=np.zeros_like(x)
print(x,type(x))
print(y,type(y))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


- 1数组

In [54]:
x=np.ones(5)
print(x,type(x))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [55]:
x=np.ones([2,3])
print(x,type(x))

[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


In [56]:
x=np.array([[1,2,3],
          [4,5,6]])
y=np.ones_like(x)
print(x,type(x))
print(y,type(y))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


- 空数组

In [57]:
n=np.empty(5)
print(n,type(n))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [58]:
n=np.empty([2,3])
print(n,type(n))

[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


In [59]:
x=np.array([[1,2,3],
          [4,5,6]])
y=np.empty_like(x)
print(x,type(x))
print(y,type(y))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


### 单位数组
- eye（）函数：返回一个对角线上为1，其他地方为0的单位数组
- identity（）函数：返回一个方的单位数组

In [60]:
x=np.eye(5)
print(x,type(x))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>


In [63]:
x=np.eye(2,3)
print(x,type(x))

[[1. 0. 0.]
 [0. 1. 0.]] <class 'numpy.ndarray'>


In [64]:
x=np.identity(4)
print(x,type(x))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] <class 'numpy.ndarray'>


### 对角数组
- diag()函数：提取对角线或者构造对角数组

In [77]:
x=np.arange(10,19).reshape((3,3))
print(x,type(x))
print('输出数组的对角线上的数字：',np.diag(x))
print('输出向上平移一步的对角线：',np.diag(x,k=1))
print('输出向下平移一部的对角线：',np.diag(x,k=-1))

[[10 11 12]
 [13 14 15]
 [16 17 18]] <class 'numpy.ndarray'>
输出数组的对角线上的数字： [10 14 18]
输出向上平移一步的对角线： [11 15]
输出向下平移一部的对角线： [13 17]


3x3的数组，对角线有有三条，往上下平移得到两条，k默认为0，指最中间的那条，向上+1，向下-1

### 常数数组
- full()函数：返回一个常数数组
- full_like()函数：返回与给定数组相似的形状和类型的常数数组

In [78]:
x=np.full((2,),7)
print(x,type(x))

[7 7] <class 'numpy.ndarray'>


In [79]:
x=np.full(2,7)
print(x,type(x))

[7 7] <class 'numpy.ndarray'>


In [81]:
x=np.full((3,4),5)
print(x,type(x))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]] <class 'numpy.ndarray'>


In [83]:
x=np.array([[1,2,3],
           [3,4,5]])
y=np.full_like(x,8)
print(y,type(y))

[[8 8 8]
 [8 8 8]] <class 'numpy.ndarray'>


### 利用数值范围来创建ndarray
- arange()函数：返回给定间隔内的均匀间隔的值
- linespace()函数：返回指定间隔内的等间隔数字
- logspace()函数：返回数以对数刻度分布均匀分布
- numpy.random.rand()：返回一个由[0，1)内的随机数组成的数组

In [84]:
x=np.arange(5)
print(x,type(x))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [85]:
x=np.arange(1,9,2)
print(x,type(x))

[1 3 5 7] <class 'numpy.ndarray'>


In [86]:
x=np.linspace(start=0,stop=2,num=9)
print(x,type(x))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] <class 'numpy.ndarray'>


In [88]:
x=np.logspace(0,1,5)
print(np.around(x,2))

[ 1.    1.78  3.16  5.62 10.  ]


In [89]:
x = np.linspace(start=0, stop=1, num=5)
x = [10 ** i for i in x]
print(np.around(x, 2))

[ 1.    1.78  3.16  5.62 10.  ]


In [90]:
x = np.random.random(5)
print(x)

[0.14525983 0.8650746  0.13547021 0.71788577 0.67032493]


In [92]:
x = np.random.random([2,3])
print(x,type(x))

[[0.56098337 0.64933814 0.58632084]
 [0.13975688 0.67226493 0.78020954]] <class 'numpy.ndarray'>


### 结构数组的创建
结构数组，首先需要定义结构，然后利用np.array()来创建数组，其中参数dtype为定义的结构

- 利用字典来定义结构

In [94]:
pType=np.dtype({'names':['name','age','weight'],
               'formats':['U30','i8','f8']})
a=np.array([('liming',24,64.5),
           ('mike',25,66),
           ('anna',32,50)],
          dtype=pType)
print(a,type(a))

[('liming', 24, 64.5) ('mike', 25, 66. ) ('anna', 32, 50. )] <class 'numpy.ndarray'>


- 利用包含多个元组的列表来定义结构

In [100]:
pType=np.dtype({'names':['name','age','weight'],
               'formats':['U30','i8','f8']})
a=np.array([('liming',24,64.5),
           ('mike',25,66),
           ('anna',32,50)],
          dtype=pType)
print('数组全部元素:',a,type(a))
print('数组第一个元素:',a[0])
print('数组倒数两个元素：',a[-2:])
print('数组中所有人名：',a['name'])
print('数组中所有人年纪：',a['age'])
print('数组中所有人年纪：',a['weight'])


数组全部元素: [('liming', 24, 64.5) ('mike', 25, 66. ) ('anna', 32, 50. )] <class 'numpy.ndarray'>
数组第一个元素: ('liming', 24, 64.5)
数组倒数两个元素： [('mike', 25, 66.) ('anna', 32, 50.)]
数组中所有人名： ['liming' 'mike' 'anna']
数组中所有人年纪： [24 25 32]
数组中所有人年纪： [64.5 66.  50. ]


## 数组的属性
- numpy.ndarray.ndim用于返回数组的维数，也称为秩，一维的秩是1，二维我i数组的秩是2，以此类推
- numpy.ndarray.shape表示数组的维度，返回一个元组，这个元组的长度就是一个维度的数目，即ndim属性（秩）
- numpy.ndarray.size表示数组内所有元素的总量，相当于数组的shape中所有的元素的乘积，例如矩阵中的元素的总量是行列的乘积
- numpy.adarray.dtype:ndarray对象的数据类型
- numpy.adarray.itemsize以字节的形式返回数组中的每一个元素的大小

In [102]:
a=np.array([1,2,3,4,5])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(a.itemsize)

(5,)
int32
5
1
4


In [104]:
b=np.array([[1,2,3,4],[5,6,7,8.0]])
print(b.shape)
print(b.dtype)
print(b.size)
print(b.ndim)
print(b.itemsize)

(2, 4)
float64
8
2
8


在ndarray中所有的元素必须是同一种类型，否则就会自动向下转换int->float->str

In [111]:
x=np.array([1,2,3,4])
print(x,x.dtype)

[1 2 3 4] int32


In [109]:
x=np.array([1,2,3,4.0])
print(x,x.dtype)

[1. 2. 3. 4.] float64


In [108]:
x=np.array([1,2,3,'4'])
print(x,x.dtype)

['1' '2' '3' '4'] <U11
