## 集合操作
### 构造集合
- numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
- return_index=True 表示返回新列表元素在旧列表中的位置。
- return_inverse=True表示返回旧列表元素在新列表中的位置。
- return_counts=True表示返回新列表元素在旧列表中出现的次数

In [1]:
import numpy as np


In [11]:
x = np.unique([1, 1, 3, 2, 3, 3])
print('=================打印集合，集合中会去重=====================')
print(x)   


x = sorted(set([1, 1, 3, 2, 3, 3]))
print('================打印集合、去重并排序======================')
print(x)   

x = np.array([[1, 1], [2, 3]])
u = np.unique(x)
print('==============输出集合，去重========================')
print(u)   

x = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
y = np.unique(x, axis=0)
print('=============对数组元素进行去重=========================')
print(y)


x = np.array(['a', 'b', 'b', 'c', 'a'])
u, index = np.unique(x, return_index=True)
print('==============打印集合元素，去重========================')
print(u)   

print('==============打印索引========================')
print(index)  
print('=================打印索引对应元素=====================')
print(x[index])





=================打印集合，集合中会去重=====================
[1 2 3]
================打印集合、去重并排序======================
[1, 2, 3]
==============输出集合，去重========================
[1 2 3]
=============对数组元素进行去重=========================
[[1 0 0]
 [2 3 4]]
==============打印集合元素，去重========================
['a' 'b' 'c']
==============打印索引========================
[0 1 3]
=================打印索引对应元素=====================
['a' 'b' 'c']


In [12]:
x = np.array([1, 2, 6, 4, 2, 3, 2])
u, index = np.unique(x, return_inverse=True)
print('=============打印集合元素=========================')
print(u) 

print('=============打印集合元素的索引=========================')
print(index) 
print('===============打印对应索引的元素=======================')
print(u[index]) 


u, count = np.unique(x, return_counts=True)
print('================打印集合元素======================')
print(u)   
print('==================统计对应位置的元素数量====================')
print(count)  

=============打印集合元素=========================
[1 2 3 4 6]
=============打印集合元素的索引=========================
[0 1 4 3 1 2 1]
===============打印对应索引的元素=======================
[1 2 6 4 2 3 2]
================打印集合元素======================
[1 2 3 4 6]
==================统计对应位置的元素数量====================
[1 3 1 1 1]


### 布尔运算
- numpy.in1d(ar1, ar2, assume_unique=False, invert=False) 


In [13]:
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
mask = np.in1d(test, states)
# 判断数组一中有没有数组二中的元素，如果有，对应的索引位置就返回true，没有就false
print(mask)   
# test数组中true的索引位对应的元素
print(test[mask])   

mask = np.in1d(test, states, invert=True)
# invert是反向的意思，就是对应位置是false，否则true
print(mask)   
print(test[mask])   

[ True False  True False  True]
[0 2 0]
[False  True False  True False]
[1 5]


### 集合的交集
- numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)

In [16]:
from functools import reduce

x = np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
print(x) 


x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
# 
# print(np.intersect1d(x, y, return_indices=True))
# 交集看i中存在的元素在集合1中第一出现的位置的索引
print(x_ind)  
# 公共元素在集合2中第一次出现的位置
print(y_ind)  
# 交集中的元素
print(xy)  
# 第一个数组中公共的数组元素
print(x[x_ind])  
# 第二个数组中，交集中的元素
print(y[y_ind])  

x = reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
# 统计共同元素
print(x)  

[1 3]
(array([1, 2, 4]), array([0, 2, 4], dtype=int64), array([1, 0, 2], dtype=int64))
[0 2 4]
[1 0 2]
[1 2 4]
[1 2 4]
[1 2 4]
[3]


### 集合的并集
- numpy.union1d(ar1, ar2)

In [19]:
x = np.union1d([-1, 0, 1], [-2, 0, 2])
print(x)  
x = reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x) 

[-2 -1  0  1  2]
[1 2 3 4 6]


### 集合的差集
- numpy.setdiff1d(ar1, ar2, assume_unique=False) 

In [20]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setdiff1d(a, b)
# 输出集合a中有的但是集合b中没有的元素相当于a-b
print(x)  

[1 2]


### 集合的异或
- setxor1d(ar1, ar2, assume_unique=False)

In [21]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setxor1d(a, b)

# 集合的交集的补集，就是两个集合各自独有的元素的集合
print(x) 

[1 2 5 6]
